--------------------------------------------------------
--  File created - Cuma-Mayýs-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARDUÝNO_TABLE
--------------------------------------------------------

  CREATE TABLE "HR"."ARDUÝNO_TABLE" 
   (	"ÝD" VARCHAR2(20 BYTE), 
	"MÝCRODENETLEYÝCÝ" VARCHAR2(20 BYTE), 
	"DÝGÝTAL_GÝRÝS_CÝKÝS" VARCHAR2(20 BYTE), 
	"PWM" VARCHAR2(20 BYTE), 
	"ANALOG_GÝRÝS" VARCHAR2(20 BYTE), 
	"FLASH_HAFÝZA" VARCHAR2(20 BYTE), 
	"SRAM" VARCHAR2(20 BYTE), 
	"EEPROM" VARCHAR2(20 BYTE), 
	"RESÝM" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.ARDUÝNO_TABLE
SET DEFINE OFF;
Insert into HR.ARDUÝNO_TABLE (ÝD,MÝCRODENETLEYÝCÝ,DÝGÝTAL_GÝRÝS_CÝKÝS,PWM,ANALOG_GÝRÝS,FLASH_HAFÝZA,SRAM,EEPROM,RESÝM) values ('r5','Arduino Micro','14','6','6','512KB','30KB','4KB','~/resimler/Arduino Micro_urunler_.jpg');
Insert into HR.ARDUÝNO_TABLE (ÝD,MÝCRODENETLEYÝCÝ,DÝGÝTAL_GÝRÝS_CÝKÝS,PWM,ANALOG_GÝRÝS,FLASH_HAFÝZA,SRAM,EEPROM,RESÝM) values ('r6','Arduino Nano','14','6','6','512KB','30KB','4KB','~/resimler/Arduino Nano_urunler_.jpg');
Insert into HR.ARDUÝNO_TABLE (ÝD,MÝCRODENETLEYÝCÝ,DÝGÝTAL_GÝRÝS_CÝKÝS,PWM,ANALOG_GÝRÝS,FLASH_HAFÝZA,SRAM,EEPROM,RESÝM) values ('r20','nano','14','6','6','312KB','30KB','2KB','~/resimler/nano_urunler_.jpg');
Insert into HR.ARDUÝNO_TABLE (ÝD,MÝCRODENETLEYÝCÝ,DÝGÝTAL_GÝRÝS_CÝKÝS,PWM,ANALOG_GÝRÝS,FLASH_HAFÝZA,SRAM,EEPROM,RESÝM) values ('r7','Arduino Uno','14','6','6','512KB','30KB','4KB','~/resimler/Arduino Uno_urunler_.jpg');
Insert into HR.ARDUÝNO_TABLE (ÝD,MÝCRODENETLEYÝCÝ,DÝGÝTAL_GÝRÝS_CÝKÝS,PWM,ANALOG_GÝRÝS,FLASH_HAFÝZA,SRAM,EEPROM,RESÝM) values ('a20','nano','10','10','10','10','10','15','~/resimler/nano_urunler_.jpg');
--------------------------------------------------------
--  DDL for Index ARDUÝNO_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ARDUÝNO_TABLE_PK" ON "HR"."ARDUÝNO_TABLE" ("ÝD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARDUÝNO_TABLE
--------------------------------------------------------

  ALTER TABLE "HR"."ARDUÝNO_TABLE" ADD CONSTRAINT "ARDUÝNO_TABLE_PK" PRIMARY KEY ("ÝD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("RESÝM" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("EEPROM" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("SRAM" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("FLASH_HAFÝZA" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("ANALOG_GÝRÝS" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("PWM" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("DÝGÝTAL_GÝRÝS_CÝKÝS" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("MÝCRODENETLEYÝCÝ" NOT NULL ENABLE);
  ALTER TABLE "HR"."ARDUÝNO_TABLE" MODIFY ("ÝD" NOT NULL ENABLE);
